config/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('baton/', include('baton.urls')),
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
    path('accounts/', include('allauth.urls')),
    path('photo/', include('photo.urls')),
    path('scard/', include('scard.urls')),
    path('chart/', include('chart.urls')),
    path('video/', include('video.urls')),
    path('golf/', include('golf.urls')),
    path('weather/', include('weather.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name="password_reset"),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'common.views.page_not_found'

golf/urls.py
from django.contrib import admin
from django.urls import path, include
from golf import views


app_name = 'golf'

urlpatterns = [

    path('golfrule', views.golfrule, name='golfrule'),
    path('screengolf', views.screengolf, name='screengolf'),
    path('map', views.map, name='map'),

]

photo/urls.py
from django.urls import path

from photo import views


app_name = 'photo'
urlpatterns = [

    # Example: /photo/
    path('', views.AlbumLV.as_view(), name='album_list'),

    # Example: /photo/album/, same as /photo/
    path('album', views.AlbumLV.as_view(), name='album_list'),

    # Example: /photo/album/99/
    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),

    # Example: /photo/photo/99/
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),

    # Example: /photo/album/add/
    path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),

    # Example: /photo/album/change/
    path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),

    # Example: /photo/album/99/update/
    path('album/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album_update'),

    # Example: /photo/album/99/delete/
    path('album/<int:pk>/delete/', views.AlbumDelV.as_view(), name='album_delete'),

    # Example: /photo/photo/add/
    path('photo/add/', views.PhotoCV.as_view(), name='photo_add'),

    # Example: /photo/photo/change/
    path('photo/change/', views.PhotoChangeLV.as_view(), name='photo_change'),

    # Example: /photo/photo/99/update/
    path('photo/<int:pk>/update/', views.PhotoUV.as_view(), name='photo_update'),

    # Example: /photo/photo/99/delete/
    path('photo/<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo_delete'),

 

]

photo/models.py
from django.db import models
from django.urls import reverse

from photo.fields import ThumbnailImageField
import subprocess



class Album(models.Model):
    name = models.CharField('NAME', max_length=30)
    description = models.CharField('One Line Description', max_length=100, blank=True)
    owner = models.ForeignKey('common.User', on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))


class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    title = models.CharField('TITLE', max_length=30)
    description = models.TextField('Photo Description', blank=True)
    image = ThumbnailImageField('IMAGE', upload_to='photo/%Y/%m')
    upload_dt = models.DateTimeField('UPLOAD DATE', auto_now_add=True)
    owner = models.ForeignKey('common.User', on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

photo/forms.py
from django.forms import inlineformset_factory  
from photo.models import Album, Photo  


PhotoInlineFormSet = inlineformset_factory(Album, Photo,
    fields = ['image', 'title', 'description'], 
    extra = 2)

photo/views.py
from django.views.generic import ListView, DetailView
from photo.models import Album, Photo

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from config.views import OwnerOnlyMixin
from photo.forms import PhotoInlineFormSet
import ffmpeg
import sys
import requests

# def upload_video(request):
     
#     if request.method == 'POST': 
         
#         title = request.POST['title']
#         video = request.POST['video']
#         video_path = 'videos/%Y/%m'
#         image_path = 'videos/%Y/%m'
#         time = '00:00:00.000'
#         video_thumbnail = generate_thumbnail(video, video_thum)
#         content = Videos(title=title,video=video,video_thumbnail=video_thumbnail)
#         content.save()

#         return redirect('videos_display')
     
#     return render(request,'photo/video_upload.html')

# def generate_thumbnail(in_filename, out_filename):
#     probe = ffmpeg.probe(in_filename)
#     time = float(probe['streams'][0]['duration']) // 2
#     width = probe['streams'][0]['width']
#     try:
#         (
#             ffmpeg
#             .input(in_filename, ss=time)
#             .filter('scale', width, -1)
#             .output(out_filename, vframes=1)
#             .overwrite_output()
#             .run(capture_stdout=True, capture_stderr=True)
#         )
#     except ffmpeg.Error as e:
#         print(e.stderr.decode(), file=sys.stderr)
#         sys.exit(1)


# def display(request):
     
#     videos = Videos.objects.all()
#     context ={
#         'videos':videos,
#     }
     
#     return render(request,'photo/videos_display.html',context)




class AlbumLV(ListView):
    model = Album


class AlbumDV(DetailView):
    model = Album


class PhotoDV(DetailView):
    model = Photo

#--- Create/Change-list/Update/Delete for Photo
class PhotoCV(LoginRequiredMixin, CreateView):
    login_url='common:login'
    model = Photo
    fields = ('album', 'title', 'image', 'description')
    success_url = reverse_lazy('photo:album_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class PhotoChangeLV(LoginRequiredMixin, ListView):
    login_url='common:login'
    model = Photo
    template_name = 'photo/photo_change_list.html'

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)


class PhotoUV(OwnerOnlyMixin, UpdateView):
    model = Photo
    fields = ('album', 'title', 'image', 'description')
    success_url = reverse_lazy('photo:album_list')


class PhotoDelV(OwnerOnlyMixin, DeleteView):
    model = Photo
    success_url = reverse_lazy('photo:photo_change')


#--- Change-list/Delete for Album
class AlbumChangeLV(LoginRequiredMixin, ListView):
    login_url='common:login'
    model = Album
    template_name = 'photo/album_change_list.html'

    def get_queryset(self):
        return Album.objects.filter(owner=self.request.user)


class AlbumDelV(OwnerOnlyMixin, DeleteView):
    model = Album
    success_url = reverse_lazy('photo:album_list')


#--- (InlineFormSet) Create/Update for Album
class AlbumPhotoCV(LoginRequiredMixin, CreateView):
    login_url='common:login'
    model = Album
    fields = ('name', 'description')
    success_url = reverse_lazy('photo:album_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = PhotoInlineFormSet()
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for photoform in formset:
            photoform.instance.owner = self.request.user
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))


class AlbumPhotoUV(OwnerOnlyMixin, UpdateView):
    model = Album
    fields = ('name', 'description')
    success_url = reverse_lazy('photo:album_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = PhotoInlineFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

templates/photo/album_change_list.html
{% extends 'main_base.html' %}
{% load static %}

{% block content %}
{% load socialaccount %}
<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}" title="Main 화면으로">SmartHAN</a></li>
        <li class="breadcrumb-item">사진</li>
        <li class="breadcrumb-item active">변경</li>
        <li class="position-absolute pos-top pos-right d-none d-sm-block"><span class="js-get-date"></span></li>
    </ol>
    <!-- <div class="subheader">
        <h1 class="subheader-title">
            <i class='fal fa-info-circle'></i> 소개
            <small>
                앨범 추가
            </small>
        </h1>
    </div> -->
    <div class="fs-lg fw-300 p-5 bg-white border-faded rounded mb-g">

        <h1>Album Change - {{user}}</h1>

        <table class="table table-striped table-bordered table-condensed">

            <thead>
            <tr class="table-success">
                <th>Name</th>
                <th>Description</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
            </thead>

            <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'photo:album_update' item.id %}">Update</a></td>
                <td><a href="{% url 'photo:album_delete' item.id %}">Delete</a></td>
            </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
{% endblock %}

templates/photo/album_confirm_delete.html
{% extends 'main_base.html' %}
{% load static %}

{% block content %}
{% load socialaccount %}
<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}" title="Main 화면으로">SmartHAN</a></li>
        <li class="breadcrumb-item">Main</li>
        <li class="breadcrumb-item active">Introduction</li>
        <li class="position-absolute pos-top pos-right d-none d-sm-block"><span class="js-get-date"></span></li>
    </ol>
    <div class="subheader">
        <h1 class="subheader-title">
            <i class='fal fa-info-circle'></i> 소개
            <small>
                이 사이트의 간단한 소개입니다.
            </small>
        </h1>
    </div>
    <div class="fs-lg fw-300 p-5 bg-white border-faded rounded mb-g">

        <h1>Album Delete <small class="font-italic">(including related photos)</small></h1>
        <br>

        <form action="." method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}" ?</p>
            <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
        </form>
    </div>
{% endblock %}

templates/photo/album_detail.html
{% extends 'main_base.html' %}
{% load static %}

{% block content %}

<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}" title="Main 화면으로">SmartHAN</a></li>
        <li class="breadcrumb-item">Main</li>
        <li class="breadcrumb-item active">Introduction</li>
        <li class="position-absolute pos-top pos-right d-none d-sm-block"><span class="js-get-date"></span></li>
    </ol>
    <div class="subheader">
        <h1 class="subheader-title">
            <i class='fal fa-info-circle'></i> 소개
            <small>
                이 사이트의 간단한 소개입니다.
            </small>
        </h1>
    </div>



    <div class="row">
        <div class="col-xl-12">
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        <a class="h2" href="">
                            {{ object.name }}</a>&emsp;
                        <span class="font-italic h5">{{ object.description }}</span>
                    </h2>
                    <div class="panel-toolbar">
                        <button class="btn btn-panel waves-effect waves-themed" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                        <button class="btn btn-panel waves-effect waves-themed" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                        <button class="btn btn-panel waves-effect waves-themed" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
                    </div>
                </div>
                <div class="panel-container show">
                    <div class="panel-content">
                        <div id="js-lightgallery" >
                            <div class="card-group">
                                {% for photo in object.photo_set.all %} 
                                <div class="card">
                                    <div class="w-100 bg-fusion-50 rounded-top border-top-right-radius-0" style="padding:10px 0 10px;"></div>
                                    <div class="card-body">
                                        <h5 class="card-title">{{ photo.title }}</h5>
                                        <a class="jg-entry entry-visible" href="{{ photo.get_absolute_url }}">
                                            <img class="img-responsive" src="{{ photo.image.thumb_url }}" alt="image"></a>
                                        <p class="card-text">{{ photo.upload_dt|date:"Y-m-d" }}</p>
                                        <small class="text-muted">Last updated 3 mins ago</small>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>  

</main>






{% endblock %}

templates/photo/album_list.html
{% extends 'main_base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" media="screen, print" href="{% static 'css/miscellaneous/lightgallery/lightgallery.bundle.css' %}">
{% endblock %}

{% block content %}

<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">SmartHAN</a></li>
        <li class="breadcrumb-item">앨범</li>
        <li class="breadcrumb-item active">리스트</li>
        <li class="position-absolute pos-top pos-right d-none d-sm-block"><span class="js-get-date"></span></li>
    </ol>
    <!-- <div class="subheader">
        <h1 class="subheader-title">
            <i class='fal fa-info-circle'></i> 소개
            <small>
                이 사이트의 간단한 소개입니다.
            </small>
        </h1>
    </div> -->



    
    <div class="row">
        <div class="col-xl-12">
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        <a class="h2" href="">
                            전체 앨범 사진들</a>&emsp;
                        <span class="font-italic h5">그림을 클릭하세요.</span>
                    </h2>
                    <div class="panel-toolbar">
                        <button class="btn btn-panel waves-effect waves-themed" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                        <button class="btn btn-panel waves-effect waves-themed" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                        <button class="btn btn-panel waves-effect waves-themed" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
                    </div>
                </div>
                <div class="panel-container show">
                    <div class="panel-content">
                        <div id="js-lightgallery" >
                        {% for item in object_list %} 
                            {% for photo in item.photo_set.all %}
                            
                            <a class="jg-entry entry-visible" href="{{ photo.image.url }}">
                                <img class="img-responsive" src="{{ photo.image.thumb_url }}" alt="{{ photo.title }}">
                            </a>
                            
                            {% endfor %}                           
                        {% endfor %}    
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>           
   





    {% for item in object_list %}
    <div class="row">
        <div class="col-xl-12">
            <div id="panel-1" class="panel panel-collapsed">
                <div class="panel-hdr">
                    <h2>
                        <a class="h2" href="{% url 'photo:album_detail' item.id %}">
                            {{ item.name }}</a>&emsp;
                        <span class="font-italic h5">{{ item.description }}</span>
                        
                    </h2>
                    <div class="panel-toolbar">
                        <button class="btn btn-panel waves-effect waves-themed" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                        <button class="btn btn-panel waves-effect waves-themed" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                        <button class="btn btn-panel waves-effect waves-themed" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
                    </div>
                </div>
                <div class="panel-container show">
                    <div class="panel-content">
                        <div id="js-lightgallery" >
                            {% for photo in item.photo_set.all %}
                            
                            <a class="jg-entry entry-visible" href="{{ photo.image.url }}">
                                <img class="img-responsive" src="{{ photo.image.thumb_url }}" alt="image"  >
                            </a>
                            
                            {% endfor %}                           
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>           
    {% endfor %}

</main>

{% endblock %}


{% block script %}
<script src="{% static 'js/miscellaneous/lightgallery/lightgallery.bundle.js' %}"></script>
<script>
    $(document).ready(function()
    {
        var $initScope = $('#js-lightgallery');
        if ($initScope.length)
        {
            $initScope.justifiedGallery(
            {
                border: -1,
                rowHeight: 150,
                margins: 8,
                waitThumbnailsLoad: true,
                randomize: false,
            }).on('jg.complete', function()
            {
                $initScope.lightGallery(
                {
                    thumbnail: true,
                    animateThumb: true,
                    showThumbByDefault: true,
                });
            });
        };
        $initScope.on('onAfterOpen.lg', function(event)
        {
            $('body').addClass("overflow-hidden");
        });
        $initScope.on('onCloseAfter.lg', function(event)
        {
            $('body').removeClass("overflow-hidden");
        });
    });

</script>
{% endblock %}

templates/photo/photo_change_list.html
{% extends 'main_base.html' %}
{% load static %}

{% block content %}
{% load socialaccount %}
<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}" title="Main 화면으로">SmartHAN</a></li>
        <li class="breadcrumb-item">사진</li>
        <li class="breadcrumb-item active">변경</li>
        <li class="position-absolute pos-top pos-right d-none d-sm-block"><span class="js-get-date"></span></li>
    </ol>
    <!-- <div class="subheader">
        <h1 class="subheader-title">
            <i class='fal fa-info-circle'></i> 이곳은
            <small>
                사진을 변경/삭제 하는 곳
            </small>
        </h1>
    </div> -->

    
    <div class="row">
        <div class="col-xl-12">
            <div id="panel-1" class="panel panel-collapsed">
                <div class="panel-hdr">
                    <h2>
                        <a class="h2" href="">
                            사진 변경/삭제 - {{user}}님</a>
                        <span class="font-italic h5">이 올리신 사진을 변경하거나 삭제 할수 있어요</span>
                    </h2>
                    <div class="panel-toolbar">
                        <button class="btn btn-panel waves-effect waves-themed" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                        <button class="btn btn-panel waves-effect waves-themed" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                        <button class="btn btn-panel waves-effect waves-themed" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
                    </div>
                </div>
                <div class="panel-container show">
                    <div class="panel-content">
                        <div class="card-group">
                            {% for item in object_list %}
                            <div class="card">
                                <div class="w-100 bg-fusion-50 rounded-top" style="padding:10px 0 10px;">
                                    <img class="card-img-top" src="{{ item.image.thumb_url }}" alt="image">
                                    
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title">{{ item.album }}</h5>
                                    <p class="card-text">{{ item.title }}</p>
                                    <p class="card-text">{{ item.description }}</p>
                                </div>
                                <div class="card-footer">
                                    
                                        <div class="btn-group">
                                        <a class="btn btn-warning" href="{% url 'photo:photo_update' item.id %}">Update</a>
                                        <a class="btn btn-danger" href="{% url 'photo:photo_delete' item.id %}">Delete</a>
                                        </div>
                                    
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> 

</main>
{% endblock %}

templates/photo/photo_form.html
{% extends 'main_base.html' %}
{% load static %}

{% block content %}
{% load socialaccount %}
{% load widget_tweaks %}
<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}" title="Main 화면으로">SmartHAN</a></li>
        <li class="breadcrumb-item">사진</li>
        <li class="breadcrumb-item active">등록/추가</li>
        <li class="position-absolute pos-top pos-right d-none d-sm-block"><span class="js-get-date"></span></li>
    </ol>
    <!-- <div class="subheader">
        <h1 class="subheader-title">
            <i class='fal fa-info-circle'></i> 사진 추가
            <small>
                이 사이트의 간단한 소개입니다.
            </small>
        </h1>
    </div> -->
    



    <div id="panel-1" class="panel">
        <div class="panel-hdr">
            <h2>
                사진  <span class="fw-300"><i>등록/추가</i></span>
            </h2>
            <div class="panel-toolbar">
                <button class="btn btn-panel waves-effect waves-themed" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                <button class="btn btn-panel waves-effect waves-themed" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                <button class="btn btn-panel waves-effect waves-themed" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
            </div>
        </div>
        <div class="panel-container show">
            <div class="panel-content">
                <h1>{{user}} 님! 사진 등록 및 추가 하세요.</h1>
                <p class="font-italic">이곳은 앨범에 사진을 등록하는 곳입니다.</p>
        
                {% if form.errors %}
                <div class="alert alert-danger">
                    <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
                    {{ form.errors }}
                </div>
                {% endif %}
                {% if form.is_multipart %}
                <form enctype="multipart/form-data" action="" method="post" class="was-validated dropzone needsclick">
                {% else %}
                <form action="." method="post" class="was-validated dropzone needsclick">
                {% endif %}
                {% csrf_token %}
                <!-- <form class="was-validated dropzone needsclick"> -->
                    
                    <div class="form-group row">
                        <div class="col-md-1 mb-3">
                        <label class="form-label" for="simpleinputInvalid"><h3>앨범 선택</h3></label>
                        </div>
                        <!-- {{ form.album|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }} -->
                        <div class="col-md-2 mb-3">
                            {{ form.album|add_class:"form-control" }}
                        </div>
                        <div class="col-md-3 mb-3">
                            <a href="{% url 'photo:album_add' %}" class="btn btn-outline-success btn-sm">
                            Add Album</a>
                        </div>
                    </div>

                   
                    <div class="form-group">
                        <label class="form-label"><h3>사진 선택</h3></label>
                        <div class="custom-file">
                            <input type="file"  name="image" accept="image/*" class="custom-file-input" id="id_image" required="">
                            <label class="custom-file-label" for="customFile-2">Choose file</label>
                            <div class="invalid-feedback">사진 파일을 선택하세요.</div>
                        </div>
                    </div>


              

                    
                    <div class="form-group">
                        <label class="form-label" for="simpleinputInvalid"><h3>사진 제목</h3></label>
                        <input type="text" name="title" maxlength="30" class="form-control" id="id_title" required="">
                        <div class="invalid-feedback">
                            사진 제목을 적으세요.
                        </div>
                    </div>

                  

                    
                    
                    <div class="form-group">
                        <label class="form-label" for="validationTextarea3"><h3>사진 설명</h3></label>
                        <textarea class="form-control" id="id_description" placeholder="Required example textarea" required="" rows="4"></textarea>
                        <div class="invalid-feedback">
                            사진의 간단한 설명을 적으세요.
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="offset-sm-5 col-sm-12">
                            <!-- <input type="submit" value="Submit" class="btn btn-info"/> -->
                            <button class="btn btn-primary ml-auto waves-effect waves-themed" value="Submit" type="submit">사진 등록</button>
                        </div>
                    </div>
                   

                </form>
            </div>
        </div>
    </div>
</main>
    {% endblock %}
    {% block script %}
  
    {% endblock %}