board/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views


app_name = 'board'

urlpatterns = [
    path('', views.board, name='board'),
    
    path('golfrule', views.golfrule, name='golfrule'),
    path('screengolf', views.screengolf, name='screengolf'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('comment/create/<int:post_id>/', views.comment_create, name='comment_create'),
    path('post/create/', views.post_create, name='post_create'),
    path('post/modify/<int:post_id>/', views.post_modify, name='post_modify'),
    path('post/delete/<int:post_id>/', views.post_delete, name='post_delete'),
    path('comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path('vote/post/<int:post_id>/', views.vote_post, name='vote_post'),
    path('vote/comment/<int:comment_id>/', views.vote_comment, name='vote_comment'),
    path('category/<int:category_id>', views.board_category, name='board_category'),
   
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('baton/', include('baton.urls')),
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
    path('accounts/', include('allauth.urls')),
    path('photo/', include('photo.urls')),
    path('scard/', include('scard.urls')),
    path('chart/', include('chart.urls')),
    path('video/', include('video.urls')),
    path('golf/', include('golf.urls')),
    path('weather/', include('weather.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name="password_reset"),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'common.views.page_not_found'

golf/urls.py
from django.contrib import admin
from django.urls import path, include
from golf import views


app_name = 'golf'

urlpatterns = [

    path('golfrule', views.golfrule, name='golfrule'),
    path('screengolf', views.screengolf, name='screengolf'),
    path('map', views.map, name='map'),

]

board/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
class Category(MPTTModel):
    parent = TreeForeignKey('self', blank=True, null=True, on_delete=models.CASCADE, related_name='children', db_index=True)
    title = models.CharField(max_length=128)
    # slug = models.SlugField(max_length=250, unique=True, allow_unicode=True)

    class Meta:
        ordering = ['tree_id', 'lft']

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        return self.title



class Post(models.Model):
    subject = models.CharField(max_length=200)
    content = RichTextUploadingField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='author_post')
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='voter_post')
    # category = models.CharField(max_length=20, unique=True)
    # slug = models.SlugField(max_length=250, unique=False, allow_unicode=True)
    category = TreeForeignKey('Category', null=True, blank=True, db_index=True, on_delete=models.SET_NULL,)
    head_image = models.ImageField(upload_to='board/images/%Y/%m',blank=True, null=True)
    
    def __str__(self):
        return self.subject

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='author_comment')
    voter = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='voter_comment')

board/forms.py
from django import forms
from board.models import Post, Comment





class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['subject','head_image', 'content','category' ]

        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            # 'head_image': forms.FileInput(attrs={"rows": "", "class": "file_class_name"}),
            
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }

        labels = {
            'subject': '제목',
            'head_image': '대표 이미지 선택',
            'content': '내용',
            'category': '카테고리',
            
         
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

board/views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.http import HttpResponse
from .models import Post, Comment, Category
from django.utils import timezone
from .forms import PostForm, CommentForm
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, Count
from django.http import HttpResponse, JsonResponse
import json

# from django.utils.html import strip_spaces_between_tags, strip_tags
# Create your views here.

def screengolf(request):
    return render(request, 'board/screengolf.html')



def golfrule(request):
    return render(request, 'board/golfrule.html')

def show_category(request):
    return render(request, 'board/category.html', {'category': Category.objects.all()})

def board(request):
    categoryall = Category.objects.all()
    category = Category.objects.all()
    popular_post_list = Post.objects.annotate(num_comment=Count('comment')).order_by('-num_comment', '-create_date')
    popular_post_list = popular_post_list[:3]
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어

    so = request.GET.get('so', '')  # 정렬기준
    print("so=", so)
    print("page=", page)
    print("kw=", kw)
   
     # 정렬
    if so == 'recommend':        
        post_list = Post.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        post_list = Post.objects.annotate(num_comment=Count('comment')).order_by('-num_comment', '-create_date')
    else:  # recent
        post_list = Post.objects.order_by('-create_date')
  
    if kw:
        post_list = post_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(comment__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()

      
    paginator = Paginator(post_list, 4)  # 페이지당 4개씩 보여주기
    page_obj = paginator.get_page(page)


    context = {'post_list': page_obj, 'page': page, 'kw': kw, 'so': so, 'category': category,'categoryall': categoryall, 'popular_post_list': popular_post_list}
    

    return render(request, 'board/post_list.html', context)

def board_category(request, category_id):
    categoryall = Category.objects.all()
    category = Category.objects.get(pk=category_id)
    popular_post_list = Post.objects.annotate(num_comment=Count('comment')).order_by('-num_comment', '-create_date')
    popular_post_list = popular_post_list[:3]
    page = request.GET.get('page', '1')  # 페이지
    print("categorypage=", page)
    kw = request.GET.get('kw', '')  # 검색어

    so = request.GET.get('so', 'recent')  # 정렬기준

     # 정렬
    if so == 'recommend':        
        post_list = Post.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        post_list = Post.objects.annotate(num_comment=Count('comment')).order_by('-num_comment', '-create_date')
    else:  # recent
        post_list = Post.objects.order_by('-create_date')
  
    if kw:
        post_list = post_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(comment__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()
    
    # post_list = post_list.get_descendants(include_self=True)
    post_list = post_list.filter(category__in=Category.objects.get(pk=category_id).get_descendants(include_self=True))
    
    paginator = Paginator(post_list, 4)  # 페이지당 4개씩 보여주기
    page_obj = paginator.get_page(page)
    print("category pagenater")


    context = {'post_list': page_obj, 'page': page, 'kw': kw, 'so': so, 'category': category,'categoryall': categoryall,'popular_post_list': popular_post_list}
    

    return render(request, 'board/post_list.html', context)





def detail(request, post_id):

    categoryall = Category.objects.all()
    category = Category.objects.all()
    popular_post_list = Post.objects.annotate(num_comment=Count('comment')).order_by('-num_comment', '-create_date')
    popular_post_list = popular_post_list[:3]
    





    post = get_object_or_404(Post, pk=post_id)
    context = {'post': post, 'popular_post_list': popular_post_list, 'category': category,'categoryall': categoryall, }
    return render(request, 'board/post_detail.html', context)

def comment_create(request, post_id):
    
    post = get_object_or_404(Post, pk=post_id)



    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.create_date = timezone.now()
            comment.post = post
            comment.author = request.user
            comment.save()
            # return redirect('board:detail', post_id=post.id)
            return redirect('{}#comment_{}'.format(
                resolve_url('board:detail', post_id=post.id), comment.id))
    else:
        form = CommentForm()
    context = {'post': post, 'form': form}
    return render(request, 'board/post_detail.html', context)
    
def index(request):
   return render(request, 'common/login_success.html')

@login_required(login_url='common:login')
def post_create(request):

    # ca = request.POST.get('category', '') 
   
    # if ca == '골프':
    #     category = Category.objects.get(pk=1)
    # elif ca == '식물':
    #     category = Category.objects.get(pk=2)
    # elif ca == '여행':
    #     category = Category.objects.get(pk=3)
    # else:
    #     category = Category.objects.get(pk=4)
    
    if request.method == 'POST':
        form = PostForm(request.POST)
        
        if form.is_valid():
            post = form.save(commit=False)
            post.create_date = timezone.now()
            post.author = request.user
            

            # post.category = category
            post.save()

            for headimage in request.FILES.getlist('head_image'):
               post.head_image = headimage
               post.save()



           
            return redirect('board:board')
    else:
        form = PostForm()
    context = {'form': form}
    return render(request, 'board/post_form.html', context)

@login_required(login_url='common:login')
def post_modify(request, post_id):
    
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('board:detail', post_id=post.id)
    
    # ca = request.POST.get('category', '') 
    # if ca == '골프':
    #     category = Category.objects.get(pk=1)
    # elif ca == '식물':
    #     category = Category.objects.get(pk=2)
    # elif ca == '여행':
    #     category = Category.objects.get(pk=3)
    # else:
    #     category = Category.objects.get(pk=4)
    
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.modify_date = timezone.now()  # 수정일시 저장
            # post.category = category
            post.save()
            for headimage in request.FILES.getlist('head_image'):
               post.head_image = headimage
               post.save()
            return redirect('board:detail', post_id=post.id)
    else:
        form = PostForm(instance=post)
    context = {'form': form}
    return render(request, 'board/post_form.html', context)

@login_required(login_url='common:login')
def post_delete(request, post_id):
   
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('board:detail', post_id=post.id)
    post.delete()
    return redirect('board:board')

@login_required(login_url='common:login')
def comment_modify(request, comment_id):
 
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('board:detail', post_id=comment.post.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            # return redirect('board:detail', post_id=comment.post.id)
            return redirect('{}#comment_{}'.format(
                resolve_url('board:detail', post_id=comment.post.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'comment': comment, 'form': form}
    return render(request, 'board/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete(request, comment_id):
   
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        comment.delete()
    return redirect('board:detail', post_id=comment.post.id)

@login_required(login_url='common:login')
def vote_post(request, post_id):
    
    post = get_object_or_404(Post, pk=post_id)
    if request.user == post.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        post.voter.add(request.user)
        # context = {'like_count': post.voter.count()}
    # return HttpResponse(json.dumps(context), content_type='application/json')
    return redirect('board:detail', post_id=post.id)


    




@login_required(login_url='common:login')
def vote_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user == comment.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        comment.voter.add(request.user)

templates/board/answer_form.html
{% extends 'main_base.html' %}
{% load static %}

{% block content %}
<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
        <li class="breadcrumb-item"><a href="javascript:void(0);">SmartAdmin</a></li>
        <li class="breadcrumb-item">Application Intel</li>
        <li class="breadcrumb-item">게시판</li>
        <li class="breadcrumb-item active">게시글 쓰기</li>
        <li class="position-absolute pos-top pos-right d-none d-sm-block"><span class="js-get-date"></span></li>
    </ol>
    <div class="subheader">
        <h1 class="subheader-title">
            <i class='fal fa-info-circle'></i> 게시글 쓰기
            <small>
                게시글을 써 주세요
            </small>
        </h1>
    </div>
    <div class="fs-lg fw-300 p-5 bg-white border-faded rounded mb-g">

    <div class="container">
        <div class="container my-3">
            <form method="post" class="post-form">
                {% csrf_token %}
                {% include "form_errors.html" %}
                <div class="form-group">
                    <label for="content">답변내용</label>
                    <textarea class="form-control" name="content" id="content" 
                              rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">저장하기</button>
            </form>
        </div>
        

    </div>
</main>
{% endblock %}

templates/board/category.html
{% load mptt_tags %}
<ul>
    {% recursetree category %}
        <li>
            {{ node.title }}
            {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
                
            {% endif %}
            
        </li>
        

        {% endrecursetree %}
</ul>

{% with node as friendly_node %}
{% recursetree category %}
{{ node.name }} aaa {{ friendly_node.name }}
{{ children }}
{% endrecursetree %}
{% endwith %}

templates/board/comment_form.html
{% extends 'main_base.html' %}
{% load static %}

{% block content %}
<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
        <li class="breadcrumb-item"><a href="javascript:void(0);">SmartAdmin</a></li>
        <li class="breadcrumb-item">Application Intel</li>
        <li class="breadcrumb-item">게시판</li>
        <li class="breadcrumb-item active">게시글 쓰기</li>
        <li class="position-absolute pos-top pos-right d-none d-sm-block"><span class="js-get-date"></span></li>
    </ol>
    <div class="subheader">
        <h1 class="subheader-title">
            <i class='fal fa-info-circle'></i> 게시글 쓰기
            <small>
                게시글을 써 주세요
            </small>
        </h1>
    </div>
    <div class="fs-lg fw-300 p-5 bg-white border-faded rounded mb-g">

    <div class="container">
        <div class="container my-3">
            <form method="post" class="post-form">
                {% csrf_token %}
                {% include "form_errors.html" %}
                <div class="form-group">
                    <label for="content">답변내용</label>
                    <textarea class="form-control" name="content" id="content" 
                              rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">저장하기</button>
            </form>
        </div>
        

    </div>
</main>
{% endblock %}

templates/board/post_detail.html
{% extends 'main_base.html' %}
{% load static %}

{% block content %}
{% load socialaccount %}

<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'index' %}">SmartHAN</a></li>
      <li class="breadcrumb-item"><a href="{% url 'board:board' %}">블로그</a></li>
      <li class="breadcrumb-item active">블로그상세보기</li>
      <li class="position-absolute pos-top pos-right d-none d-sm-block"><span class="js-get-date"></span></li>
    </ol>
    <!-- <div class="subheader">
      <h1 class="subheader-title">
          <i class='fal fa-info-circle'></i> 게시글 상세 보기, 댓글 달기
          <small>
              게시물을 보고 댓글을 달아 주세요.
          </small>
      </h1>
    </div> -->

      <!-- 본인이 작성한 글을 추천할 경우 에러 표시 -->
      {% if messages %}
      <div class="alert alert-primary alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">
            <i class="fal fa-times"></i>
          </span>
        </button>
        <div class="d-flex flex-start w-100">
          <div class="mr-2">
            <span class="icon-stack icon-stack-lg">
              <i class="base base-6 icon-stack-3x opacity-100 color-primary-500"></i>
              <i class="base base-10 icon-stack-2x opacity-100 color-primary-300 fa-flip-vertical"></i>
              <i class="fal fa-info icon-stack-1x opacity-100 color-white"></i>
            </span>
          </div>
          <div class="d-flex flex-fill">
            <div class="flex-fill">
              <h3 class="mb-g">
                  {% for message in messages %}
                    <strong>{{ message.tags }}</strong>
                    <ul><li>{{ message.message }}</li></ul>
                  {% endfor %}
              </h3>
            </div>
          </div>
        </div>
      </div>
      {% endif %}
      <!--  본인이 작성한 글을 추천할 경우 에러 표시 -->
    
    <div class="row">
      <div class="col-md-9 ml-auto">
        <div id="panel-1" class="panel">
          <div class="panel-hdr">
            <h2>
                <a class="h2" href="">
                    블로그 상세 보기</a>&emsp;
                <span class="font-italic h5"></span>
            </h2>
            <div class="panel-toolbar">
                <button class="btn btn-panel waves-effect waves-themed" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                <button class="btn btn-panel waves-effect waves-themed" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                <button class="btn btn-panel waves-effect waves-themed" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
            </div>
          </div>
          <div class="panel-container show">
              
                <h2 class="border-bottom py-2">
                  {{ post.subject }}
                </h2>
                <div class="card my-3">
                  <div class="card-body">
                    <!-- 대표 이미지가 있으면 불러오고, 없으면 픽숨에서 이미지를 빌려서 가지고 옴 -->
                    <div class="card-text" style="white-space: pre-line;">
                          {% if post.head_image %}
                          <img src="{{ post.head_image.url }}" class="card-img-top" alt="...">
                          {% else %}
                          <img src="https://picsum.photos/id/{{post.id}}/600/300" class="card-img-top" alt="...">
                          {% endif %}
                    </div>
                    <!-- 포스트의 내용 -->
                    <div class="card-text card-img-top" style="white-space: pre-line;">
                      {{ post.content|safe }}
                    </div>
                    
                    <!-- 수정. 생성 날짜 -->
                    <div class="d-flex justify-content-end">
                      <div class="d-inline-flex flex-column">
                          {% if post.modify_date %}
                          <div class="badge badge-light p-2">
                          고친날 : {{ post.modify_date }}
                          </div>
                          {% endif %}                    
                          <div class="badge badge-light p-2">
                          만들날: {{ post.create_date }}
                          </div>
                      </div>
                    </div>
                    <div class="d-flex justify-content-end">
                      <div class="d-inline-flex flex-column">
                          <div class="badge badge-light p-2">
                            만든분 {{ post.author.username }} 님
                          </div>
                      </div>
                      <div class="d-inline-block align-middle status status-success status-sm mr-2">
                          {% if post.author.user_image %}
                          <span class="profile-image-md rounded-circle d-block" style="background-image:url('{{post.author.user_image.url}}'); background-size: cover;"></span>
                          {% else %}
                          <span class="profile-image-md rounded-circle d-block" style="background-image:url('/media/images/avatar-f.png'); background-size: cover;"></span>
                          {% endif %}
                      </div>
                    </div>
                    <!-- 수정, 삭제, 좋아요 단추 -->
                    {% if request.user == post.author %}
                    <div class="my-3">
                        <a href="{% url 'board:post_modify' post.id  %}" 
                        class="btn btn-success btn-sm">수정</a>
                        <a href="#" class="delete btn btn-danger btn-sm"
                            data-uri="{% url 'board:post_delete' post.id %}">삭제</a>
                        <a href="#" data-uri="{% url 'board:vote_post' post.id  %}"
                            class="recommend btn btn-info btn-sm fal fa-thumbs-up">좋아요 {{post.voter.count}}</a>
                    </div>
                    {% else %}
                    <div class="my-3">
                        <a href="#" data-uri="{% url 'board:vote_post' post.id  %}"
                        class="recommend btn btn-info btn-sm fal fa-thumbs-up">좋아요 {{post.voter.count}}</a>
                    </div>
                    {% endif %}
                  </div>
                </div>

                <!-- 댓글 영역 -->
                <div class="border-bottom">
                <h5 class="my-3 py-2 badge badge-warning rounded fal fa-comment-lines"> {{post.comment_set.count}}개의 댓글이 있습니다.</h5>
                </div>


                {% for comment in post.comment_set.all %}
                <div class="media mb-3 border-bottom">
                  <div class="text-center">
                    {% if comment.author.user_image %}
                    <span class="profile-image-md rounded-circle d-block" style="background-image:url('{{comment.author.user_image.url}}'); background-size: cover;"></span>
                    {% else %}
                    <span class="profile-image-md rounded-circle d-block" style="background-image:url('/media/images/avatar-f.png'); background-size: cover;"></span>
                    {% endif %}
                    <h6 class="mt-1 mb-0 mr-3">{{ comment.author.username }}</h6><br>
                    <a href="#" data-uri="{% url 'board:vote_comment' comment.id  %}"
                            class="recommend btn btn-info btn-sm fal fa-thumbs-up"> 좋아요 {{comment.voter.count}}</a>
                  </div>
                  <div class="media-body">
                    <p class="mt-3 mb-2">{{ comment.content }}</p>
                    <div class="d-flex justify-content-end">
                    {% if comment.modify_date %}
                    <time class="timeago text-muted">
                    수정 : {{ comment.modify_date }}
                    </time>
                    {% else %}
                    <time class="timeago text-muted">
                    생성 : {{ comment.create_date }}
                    </time>
                    {% endif %}                    
                    
                    
                    {% if request.user == comment.author %}
                        <!-- <div class="my-3"> -->
                            <a href="{% url 'board:comment_modify' comment.id  %}" 
                              class="btn btn-success btn-sm">수정</a>
                            <a href="#" class="delete btn btn-danger btn-sm" 
                            data-uri="{% url 'board:comment_delete' comment.id %}">삭제</a>
                          
                        <!-- </div> -->
                        {% else %}
                        <!-- <div class="my-3"> -->
                            <!-- <a href="#" data-uri="{% url 'board:vote_comment' comment.id  %}"
                            class="recommend btn btn-info btn-sm fal fa-thumbs-up"> {{comment.voter.count}} 개</a> -->
                        <!-- </div> -->
                        {% endif %}
                      </div> 
                  </div>
                </div>
                {% endfor %}


                <form action="{% url 'board:comment_create' post.id %}" method="post" class="my-3">
                    {% csrf_token %}
                    {% if form.errors %}
                    <div class="alert alert-danger" role="alert">
                    {% for field in form %}
                    {% if field.errors %}
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                    {% endif %}
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div class="form-group">
                      <textarea class="form-control" name="content"
                      id="" rows="1">{{ form.content.value|default_if_none:'' }}</textarea>
                       
                    </div>
                   
                    <button type="submit" class="btn btn-primary">댓글달기</button>
                </form>
              
          </div>
        </div>
      </div>
      {% include "board/post_side.html" %}
    </div>
</main>
{% endblock %}

{% block script %}

<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });

    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });

    // $(".eo").on('change', function() {
    //     $("#eo").val($(this).val());
    //     $("#page").val(1);
    //     $("#searchForm").submit();
    // });

});
</script>

<script type='text/javascript'>
  $(document).ready(function(){
      $(".delete").on('click', function() {
          if(confirm("정말로 삭제하시겠습니까?")) {
              location.href = $(this).data('uri');
          }
      });
  });



</script>
<script type='text/javascript'>
  $(document).ready(function(){
      
  
      $(".recommend").on('click', function() {
          if(confirm("정말로 추천하시겠습니까?")) {
              location.href = $(this).data('uri');
          }
          
       

  
          {% if form.errors %}
          confirm("에러 발생");
          Swal.fire("aaaaaaa");
          {% endif %}
      //A title with a text under
     
      });
    
  });
</script>
<script>
  $(document).ready(function () {
    $("#cke_id_content").css("width", "100%")
 });

</script> 
{% endblock %}